name: Bot Konten Otomatis 24/7

on:
  schedule:
    # Berjalan setiap 6 jam secara otomatis
    - cron: '0 */6 * * *'
  workflow_dispatch: # Supaya bisa kita klik tombol "Run" manual buat tes

env:
  # Memaksa penggunaan Node.js 24 agar tidak ada peringatan deprecation
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari repo
        # Diperbarui ke v4 (Mendukung Node 24)
        uses: actions/checkout@v4

      - name: Siapkan Python
        # Diperbarui ke v5 (Mendukung Node 24)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instal aplikasi pendukung
        run: pip install -r requirements.txt

      - name: Jalankan Bot Pembuat Gambar
        run: python main.py

      - name: Simpan Hasil ke GitHub
        # Diperbarui ke v5 (Mendukung Node 24)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update konten otomatis [Bot]"
          file_pattern: 'hasil_konten/*.jpg'
